### ISSUE TITLE
virtcrud fails parsing VirtualBox VMs/snapshots with newline characters in description 

### ISSUE THREAD

**Issue by napkinbrown** [ottomatica/virtcrud#70]
**Given:** There exists one or more VirtualBox machines or VM snapshots with multiline descriptions.

Running:
```
bakerx run alp3.9 alpine3.9-simple
```
Gives the following error:
```
️ERROR:
C:\Users\Dominic Brown\AppData\Roaming\npm\node_modules\bakerx\node_modules\virtcrud\providers\virtualbox\VBoxProvider.js:468
                        let id = lineSplit[1].trim();
                                              ^
TypeError: Cannot read property 'trim' of undefined
    at C:\Users\Dominic Brown\AppData\Roaming\npm\node_modules\bakerx\node_modules\virtcrud\providers\virtualbox\VBoxProvider.js:468:47
    at ChildProcess.exithandler (child_process.js:299:7)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
Creating alp3.9 using vbox...
exit code: 1
```

Once the newlines from each existing descriptions is removed, the error no longer appears.

**Note:** Even though the alp3.9 does not have a description, _any_ VM that has a description with a `\n` will cause the error to appear (at least in the context of `bakerx`)

`VBoxManage showvminfo alp3.9` [alp-output](https://github.com/ottomatica/virtcrud/files/5967217/alp-output.txt)

This is a VM on my machine that has a long multiline description as well as a snapshot with a multiline description
`VBoxManage showvminfo Kali-Linux-2020.4-vbox-amd64`  [kali-output](https://github.com/ottomatica/virtcrud/files/5967232/kali-output.txt)

**Comment by chrisparnin** [comment]
https://www.virtualbox.org/ticket/12073

Virtual Box's `showvminfo` command will include the raw output of the description without escaping newlines. We will have to skip or improve parsing. They could have done something about this but choose not to:

![image](https://user-images.githubusercontent.com/742934/107864491-8f7dcc00-6e2a-11eb-8fc8-4d6c21f17025.png)

**Comment by chrisparnin** [comment]
Fixed in https://github.com/ottomatica/virtcrud/commit/fc7320ef3d3df3dc9a2441668244c9909de0a93c
